package lk.ijse.shoeshop.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lk.ijse.shoeshop.entity.CustomerEntity;
import lk.ijse.shoeshop.entity.EmployeeEntity;
import lk.ijse.shoeshop.entity.SaleItemEntity;
import lk.ijse.shoeshop.entity.enums.PaymentMethods;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class SaleDTO implements SuperDTO{
    @Null(message = "Id is autogenerated")
    private String orderId;
    @NotNull
    private Double totalPrice;
    @NotNull
    private PaymentMethods paymentMethod;
    @NotNull
    private Integer addedPoints;
    @NotNull
    private EmployeeEntity employee;
    @NotNull
    private CustomerEntity customer;
    @NotNull
    private List<SaleItemEntity> saleItems;
}