export var employeeData = {
    profilePic: null,
    employeeCode: null,
    name: null,
    gender: null,
    status: null,
    dob: null,
    joinedDate: null,
    branch: null,
    addressNo: null,
    addressLane: null,
    addressCity: null,
    addressState: null,
    postalCode: null,
    email: null,
    phone: null,
    password: null,
    guardianOrNominatedPerson: null,
    role: null,
    designation: null,
    emergencyContact: null
};
export var employees = [];

export var employeeDataInfo = {
    profilePic: null,
    employeeCode: null,
    name: null,
    gender: null,
    status: null,
    dob: null,
    joinedDate: null,
    branch: null,
    addressNo: null,
    addressLane: null,
    addressCity: null,
    addressState: null,
    postalCode: null,
    email: null,
    phone: null,
    password: null,
    guardianOrNominatedPerson: null,
    role: null,
    designation: null,
    emergencyContact: null
};